<a href="https://colab.research.google.com/github/Franck-El/github-wq9w61-6n8dyd/blob/master/openClassroom_dataAnalyze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# NUMPY (Numerical Python)

Permet de manipuler des array = liste Python dont les éléments sont tous du même type, ce qui permet d'optimiser le stockage en mémoire et donc la vitesse d'éxécution.

Si dans la liste de départ il y a des données de types différents, NumPy essaiera de tous les convertir au type le plus général.

Tableau 1D

In [ ]:
import numpy as np
liste = [1, 3.0, 5, 8, 9, 10 ,2]
array = np.array(liste)
print(type(liste))
print(type(array))
print(array.dtype) # retourne le type des éléments contenu dans l'array

<class 'list'>
<class 'numpy.ndarray'>
float64


Comme en Matlab, il est possible d'utiliser la syntaxe : nom_array[i:j:p] , avec :

* i : l’indice du début ;
* j : l’indice de fin ;
* p : le pas.

In [ ]:
print("l'élément 0 : ", array[0])
print("l'élément 1 : ",array[1])
print("le premier en partant de la fin : ",array[-1])
print("le deuxième en partant de la fin : ",array[-2])
print("les éléments 0 à 3 : ",array[0:3])
print("les éléments 0 à 6 par pas de 2 : ",array[0:3:6]) # si début vide : 0, si pas vide : 1, fin vide : la fin
print("les 2 premiers : ",array[:2])
print("après les 2 premiers : ",array[2:])
print("du 4e en partant de la fin au 2e-1 en partant de la fin : ",array[-4:-2])
print("les éléments qui sont supérieur à 5 : ", array[array>5], "car :", array>5)
print("Et (pas de and ici comparaison car terme à terme) : ", array[(array>5) & (array<9)])
print("Ou (pas de or ici comparaison car terme à terme) : ", array[(array>5) | (array<9)])

l'élément 0 :  1.0
l'élément 1 :  3.0
le premier en partant de la fin :  2.0
le deuxième en partant de la fin :  10.0
les éléments 0 à 3 :  [1. 3. 5.]
les éléments 0 à 6 par pas de 2 :  [1.]
les 2 premiers :  [1. 3.]
après les 2 premiers :  [ 5.  8.  9. 10.  2.]
du 4e en partant de la fin au 2e-1 en partant de la fin :  [8. 9.]
les éléments qui sont supérieur à 5 :  [ 8.  9. 10.] car : [False False False  True  True  True False]
Et (pas de and ici comparaison car terme à terme) :  [8.]
Ou (pas de or ici comparaison car terme à terme) :  [ 1.  3.  5.  8.  9. 10.  2.]


In [ ]:
 # début vide = 0, pas vide = 1, fin = indice final => on affiche tout
 # comme print(array), inutile mais à savoir pour comprendre l'indiçage
print(array[::])

array.sort()
print(array) # le tableau est modifié attention !

[ 1.  3.  5.  8.  9. 10.  2.]
[ 1.  2.  3.  5.  8.  9. 10.]


## Tableau N Dimensions

In [ ]:
list_part1 = [1, 2, 3, 4]
list_part2 = [5, 6, 7, 8]
list_part3 = [9, 10, 11, 12]

 # liste de listes pour représenter chaque ligne d'une matrice
complete_list = [list_part1,
                  list_part2,
                  list_part3]

# transformer la liste en un array
array_3D = np.array(complete_list)

print("listes :\n", list_part1, '\n', list_part2, '\n', list_part3)
print("liste complete:\n", complete_list)
print("array :\n", array_3D)
print(np.size(array_3D)) # n éléments /!\ != MatLab
print(np.shape(array_3D)) # n lignes, m colonnes
print(len(list_part1))
print(len(complete_list))
print(len(array_3D))


listes :
 [1, 2, 3, 4] 
 [5, 6, 7, 8] 
 [9, 10, 11, 12]
liste complete:
 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)
4
3
3


## Quelques Fonctions

In [ ]:
# calculer la moyenne
print(array.mean())

# calculer le maximum (ou le minimum)
print(array.max())
print(array.min())

# accéder à l’indice de l’élement minimum (ou maximum)
print(array.argmin())
print(array.argmax())

# ordonner par ordre croissant => array est modifié
array.sort()
print(array)

# calculer la somme
print(array.sum())

# Matlab like
i = 0
j = 50
n = 5
m = 2
print(np.linspace(i, j, n)) # [0,50] with linear space
print(np.arange(i, j, n)) # [0,50] with step 5
print( np.ones((n,m)) ) # /!\ c'est un tuple à l'intérieur
print( np.zeros((n,m)) )

# un tableau de 6x3 rempli de valeurs aléatoires comprises entre 0 et 1
print( np.random.random((6, 3)) )

# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
print( np.random.randint(1, 10, size=(3, 3)) )

5.428571428571429
10.0
1.0
0
6
[ 1.  2.  3.  5.  8.  9. 10.]
38.0
[ 0.  12.5 25.  37.5 50. ]
[ 0  5 10 15 20 25 30 35 40 45]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.10519808 0.66843843 0.6305598 ]
 [0.88928481 0.75256923 0.92738817]
 [0.3536994  0.5883798  0.06266141]
 [0.23394187 0.0863823  0.42626921]
 [0.44476165 0.01866594 0.42173293]
 [0.28950632 0.64255331 0.21981536]]
[[8 6 6]
 [2 2 8]
 [3 5 6]]


## Calcul matriciel

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])

print(A+B) # addition terme a terme
print(A-B) # soustraction terme a terme
print(A*B) # produit terme a terme
print(A**B) # puissance terme a terme

# produit matriciel, 2 ecritures
print( np.dot(A,B) )
print( A@B ) # seulement pour v.recent de Python

[[ 6 12]
 [18 24]]
[[ -4  -8]
 [-12 -16]]
[[ 5 20]
 [45 80]]
[[            1          1024]
 [     14348907 1099511627776]]
[[ 35  50]
 [ 75 110]]
[[ 35  50]
 [ 75 110]]


In [ ]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])
print(b)

[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


# Panda

In [ ]:
import pandas as pd

## Charger du csv (Data frame)

In [ ]:
path_csv = '/content/drive/MyDrive/Colab Notebooks/data/clients.csv'
data_csv = pd.read_csv(path_csv)
data_csv.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

## Charger du json (Data frame)

In [ ]:
path_json = '/content/drive/MyDrive/Colab Notebooks/data/clients.json'
data_json = pd.read_json(path_json)
data_json.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

## Charger un excel (Data frame)

In [ ]:
path_xlsx = '/content/drive/MyDrive/Colab Notebooks/data/clients.xlsx'
data_xlsx = pd.read_excel(path_xlsx)
print( 'read xlsx : \n')
print( data_xlsx.head() )
print( data_xlsx.tail() )# comme en bash
print( 'dimensions : ', data_csv.shape )
print( 'types : ', data_xlsx.dtypes )

read xlsx : 

   identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M
     identifiant                            email                nom genre
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M
dimensions :  (228, 4)
types :  identifiant     int64
email          object
nom            object
genre          object
dtype: object


## Accéder aux colonnes (Series)

In [ ]:
print( 'use id : \n')
# utilisation des id
print(type(data_xlsx)) # un tableau pandas est de type data frame
id = data_xlsx['identifiant']
id_name = data_xlsx[['identifiant', 'nom']] # attention double crochets nécessaires
print( id )
print( 'type : ', type(id)) # une colonne pandas est de type Series
print( id_name )
print( 'type : ', type(id_name) ) # un tableau => type data frame

use id : 

<class 'pandas.core.frame.DataFrame'>
0        0
1        1
2        2
3        3
4        4
      ... 
223    223
224    224
225    225
226    226
227    227
Name: identifiant, Length: 228, dtype: int64
type :  <class 'pandas.core.series.Series'>
     identifiant                nom
0              0   Laurent Dagenais
1              1         Guy Marois
2              2    Beaufort Lesage
3              3     Russell Durand
4              4        Alexis Riel
..           ...                ...
223          223  Claude Dandonneau
224          224   Apolline Michaud
225          225  Pascaline Beaudry
226          226     Fleur Caouette
227          227      Francis Masse

[228 rows x 2 columns]
type :  <class 'pandas.core.frame.DataFrame'>


## Extraire les valeurs dans un array utilisable par numpy

In [ ]:
clients_array = data_xlsx.values
# display(clients_array)
print(type(clients_array))
print(clients_array.dtype)

<class 'numpy.ndarray'>
object


Data frame et Series ont des méthodes communes et spécifiques /!\

1. Dans une Series (colonne) = un seul type
2. Dans un Data fram (tableau) = plusieurs types possible,  un par Series qui le compose

## Manipuler les colonnes

### Mettre la même valeur à chaque ligne

In [ ]:
data_xlsx['identifiant'] = 'valeur'
print(data_xlsx['identifiant']) # dtype était int64 et devient objet (les strings sont de type objet dans pandas)

0      valeur
1      valeur
2      valeur
3      valeur
4      valeur
        ...  
223    valeur
224    valeur
225    valeur
226    valeur
227    valeur
Name: identifiant, Length: 228, dtype: object


### Remplacer la colonne par une autre de meme dimension

In [ ]:
data_xlsx['identifiant'] = np.random.randint(1, 1000, clients_array.shape[0])
print(data_xlsx['identifiant'])

0      330
1      923
2      746
3      294
4      791
      ... 
223    264
224    179
225    826
226    799
227    193
Name: identifiant, Length: 228, dtype: int64


### Ajout d'une colonne

In [ ]:
data_xlsx['id'] = data_xlsx['identifiant'] + 1000
data_xlsx.head()

identifiant                      email               nom genre    id
0          330  LaurentDagenais@rhyta.com  Laurent Dagenais     M  1330
1          923      GuyMarois@fleckens.hu        Guy Marois     M  1923
2          746  BeaufortLesage@einrot.com   Beaufort Lesage     M  1746
3          294  RussellDurand@armyspy.com    Russell Durand     M  1294
4          791       AlexisRiel@rhyta.com       Alexis Riel     M  1791

### Suppression d'une colonne

#### Sans modification du Data frame

In [ ]:
data = data_xlsx.drop(columns='id')
print(data)
print(data_xlsx) # cette methode renvoie une copie modifiee

     identifiant                            email                nom genre
0            330        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1            923            GuyMarois@fleckens.hu         Guy Marois     M
2            746        BeaufortLesage@einrot.com    Beaufort Lesage     M
3            294        RussellDurand@armyspy.com     Russell Durand     M
4            791             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          264  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          179    ApollineMichaud@superrito.com   Apolline Michaud     F
225          826       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          799     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          193      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]
     identifiant                            email                nom genre  

#### Avec modification du Data frame

In [ ]:
del data_xlsx['id']
data_xlsx.head()

identifiant                      email               nom genre
0          330  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1          923      GuyMarois@fleckens.hu        Guy Marois     M
2          746  BeaufortLesage@einrot.com   Beaufort Lesage     M
3          294  RussellDurand@armyspy.com    Russell Durand     M
4          791       AlexisRiel@rhyta.com       Alexis Riel     M

In [ ]:
# modifie le data frame mais exporte la donnee pour pouvoir la conserver
data = data_xlsx # /!\ comme en JS : modifier l'un modifie l'autre, ce n'est pas une copie de valeur mais de reference
nom = data.pop('nom')
print('data_xlsx : ', data_xlsx)
print('\ndata : ', data)
print('\nnom : ', nom)

data_xlsx :       identifiant                            email genre
0            330        LaurentDagenais@rhyta.com     M
1            923            GuyMarois@fleckens.hu     M
2            746        BeaufortLesage@einrot.com     M
3            294        RussellDurand@armyspy.com     M
4            791             AlexisRiel@rhyta.com     M
..           ...                              ...   ...
223          264  ClaudeDandonneau@jourrapide.com     F
224          179    ApollineMichaud@superrito.com     F
225          826       PascalineBeaudry@rhyta.com     F
226          799     FleurCaouette@jourrapide.com     F
227          193      FrancisMasse@jourrapide.com     M

[228 rows x 3 columns]

data :       identifiant                            email genre
0            330        LaurentDagenais@rhyta.com     M
1            923            GuyMarois@fleckens.hu     M
2            746        BeaufortLesage@einrot.com     M
3            294        RussellDurand@armyspy.com     M
4 

#### Renommer des colonnes

In [ ]:
data.rename(columns={'identifiant': 'ide', 'email': 'mail'}) # Renvoie une copie sauf si propriete inplace=True (vrai pour toutes les methodes qui renvoient des copies)

ide                             mail genre
0    330        LaurentDagenais@rhyta.com     M
1    923            GuyMarois@fleckens.hu     M
2    746        BeaufortLesage@einrot.com     M
3    294        RussellDurand@armyspy.com     M
4    791             AlexisRiel@rhyta.com     M
..   ...                              ...   ...
223  264  ClaudeDandonneau@jourrapide.com     F
224  179    ApollineMichaud@superrito.com     F
225  826       PascalineBeaudry@rhyta.com     F
226  799     FleurCaouette@jourrapide.com     F
227  193      FrancisMasse@jourrapide.com     M

[228 rows x 3 columns]

#### Changer le type des données d'une colonne

In [ ]:
data['identifiant'].astype(float)

0      330.0
1      923.0
2      746.0
3      294.0
4      791.0
       ...  
223    264.0
224    179.0
225    826.0
226    799.0
227    193.0
Name: identifiant, Length: 228, dtype: float64

## Methodes de tri

In [ ]:
# trier selon l’identifiant, par ordre croissant :
data.sort_values('identifiant')

identifiant                          email genre
69             3  MusetteProvencher@armyspy.com     F
23             7     DelmareLHeureux@dayrep.com     F
98             8      NatalieLeveille@rhyta.com     F
83             9         OlivieNorbert@cuvox.de     F
148           10        OlivierAube@armyspy.com     M
..           ...                            ...   ...
209          979       JulienBeriault@rhyta.com     M
95           987  RachellePlaisance@armyspy.com     F
130          993    ElisePerrault@superrito.com     F
136          998          BriceFaure@einrot.com     M
9            998     TheodoreClavet@teleworm.us     M

[228 rows x 3 columns]

In [ ]:
#trier selon l’identifiant par ordre décroissant :
data.sort_values('identifiant', ascending = False)

identifiant                          email genre
136          998          BriceFaure@einrot.com     M
9            998     TheodoreClavet@teleworm.us     M
130          993    ElisePerrault@superrito.com     F
95           987  RachellePlaisance@armyspy.com     F
209          979       JulienBeriault@rhyta.com     M
..           ...                            ...   ...
148           10        OlivierAube@armyspy.com     M
83             9         OlivieNorbert@cuvox.de     F
98             8      NatalieLeveille@rhyta.com     F
23             7     DelmareLHeureux@dayrep.com     F
69             3  MusetteProvencher@armyspy.com     F

[228 rows x 3 columns]

In [ ]:
# trier selon le genre puis l'identifiant, par ordre croissant :
data.sort_values(['genre', 'identifiant'])

identifiant                          email genre
69             3  MusetteProvencher@armyspy.com     F
23             7     DelmareLHeureux@dayrep.com     F
98             8      NatalieLeveille@rhyta.com     F
83             9         OlivieNorbert@cuvox.de     F
89            14     HeloiseGregoire@dayrep.com     F
..           ...                            ...   ...
47           966      FranckBinet@superrito.com     M
12           971   NormandArsenault@armyspy.com     M
209          979       JulienBeriault@rhyta.com     M
9            998     TheodoreClavet@teleworm.us     M
136          998          BriceFaure@einrot.com     M

[228 rows x 3 columns]

In [ ]:
# trier selon le genre puis l'identifiant, en precisant l'ordre croissant ou decroissant par donnee
data.sort_values(['genre', 'identifiant'], ascending=[True, False])

identifiant                          email genre
130          993    ElisePerrault@superrito.com     F
95           987  RachellePlaisance@armyspy.com     F
99           945    SydneyGuibord@superrito.com     F
153          921  DanielleNeufville@teleworm.us     F
85           894  AstridJolicoeur@superrito.com     F
..           ...                            ...   ...
88            43       AlexisLagrange@gustr.com     M
11            30         FlorusDevoe@einrot.com     M
187           28     KarelDandonneau@dayrep.com     M
5             22          LeonLapresse@cuvox.de     M
148           10        OlivierAube@armyspy.com     M

[228 rows x 3 columns]

## Selection par indices 'iloc'

In [ ]:
# selectionner toutes les colonnes des 10 premiers clients :
print( data.iloc[:10, :] )

# selectionner l’email et le genre des clients 10 à 20-1
print( data.iloc[10:20, 1:3] )

# sélectionner l’e-mail et le genre des 10 derniers clients :
print( data.iloc[-10:, [1, 2]] )

   identifiant                          email genre
0          330      LaurentDagenais@rhyta.com     M
1          923          GuyMarois@fleckens.hu     M
2          746      BeaufortLesage@einrot.com     M
3          294      RussellDurand@armyspy.com     M
4          791           AlexisRiel@rhyta.com     M
5           22          LeonLapresse@cuvox.de     M
6          567      OrvilleRouthier@gustr.com     M
7          479       AgramantPepin@dayrep.com     M
8          328  AiglentinaLambert@fleckens.hu     F
9          998     TheodoreClavet@teleworm.us     M
                             email genre
10    ByronLefebvre@jourrapide.com     M
11          FlorusDevoe@einrot.com     M
12    NormandArsenault@armyspy.com     M
13    AcelineHughes@jourrapide.com     F
14    GastonBrisette@superrito.com     M
15        AgateGrandbois@gustr.com     F
16  AgricanFoucault@jourrapide.com     M
17   PrunellaJosseaume@armyspy.com     F
18       YseultCharest@armyspy.com     F
19          Doroth

## Selection par index ou condition 'loc'

- mon_dataframe.loc[ condition sur les lignes, colonne(s) ]
- mon_dataframe.loc[ index, numéro de colonne ]

In [ ]:
data.loc[data['genre'] == 'M', :]

identifiant                        email genre
0            330    LaurentDagenais@rhyta.com     M
1            923        GuyMarois@fleckens.hu     M
2            746    BeaufortLesage@einrot.com     M
3            294    RussellDurand@armyspy.com     M
4            791         AlexisRiel@rhyta.com     M
..           ...                          ...   ...
217           88         GanoHetu@fleckens.hu     M
219          636     RoslynChalifour@cuvox.de     M
220          109      KarelBazinet@einrot.com     M
222          408     LangleyCaron@armyspy.com     M
227          193  FrancisMasse@jourrapide.com     M

[110 rows x 3 columns]

In [ ]:
display(data.loc[0:10, :])
display(data.loc[0:10, :].index)
display(data.iloc[0:10, :])
print(data.iloc[0:10, :].index)

identifiant                          email genre
0           330      LaurentDagenais@rhyta.com     M
1           923          GuyMarois@fleckens.hu     M
2           746      BeaufortLesage@einrot.com     M
3           294      RussellDurand@armyspy.com     M
4           791           AlexisRiel@rhyta.com     M
5            22          LeonLapresse@cuvox.de     M
6           567      OrvilleRouthier@gustr.com     M
7           479       AgramantPepin@dayrep.com     M
8           328  AiglentinaLambert@fleckens.hu     F
9           998     TheodoreClavet@teleworm.us     M
10           89   ByronLefebvre@jourrapide.com     M

RangeIndex(start=0, stop=11, step=1)

identifiant                          email genre
0          330      LaurentDagenais@rhyta.com     M
1          923          GuyMarois@fleckens.hu     M
2          746      BeaufortLesage@einrot.com     M
3          294      RussellDurand@armyspy.com     M
4          791           AlexisRiel@rhyta.com     M
5           22          LeonLapresse@cuvox.de     M
6          567      OrvilleRouthier@gustr.com     M
7          479       AgramantPepin@dayrep.com     M
8          328  AiglentinaLambert@fleckens.hu     F
9          998     TheodoreClavet@teleworm.us     M

RangeIndex(start=0, stop=10, step=1)


In [ ]:
# création d’un data frame trié avant de ‘désordonner’ les Index
df_temp = data.sort_values('email')
display(df_temp)
display(df_temp.reset_index())
display(df_temp.reset_index(drop=True)) # sans garder les anciens Index

identifiant                         email genre
13            39  AcelineHughes@jourrapide.com     F
135          431     AdelaideBrousse@gustr.com     F
189          762        AdeleClavette@cuvox.de     F
15           150      AgateGrandbois@gustr.com     F
180          853          AgnesBriard@cuvox.de     F
..           ...                           ...   ...
64           320          YvetteDAvis@cuvox.de     F
174          567   ZacharieDuplessis@rhyta.com     M
100          144   ZdenekVadnais@superrito.com     M
112          302          ZoeLeclair@gustr.com     F
53           615       ZurieTheberge@gustr.com     F

[228 rows x 3 columns]

index  identifiant                         email genre
0       13           39  AcelineHughes@jourrapide.com     F
1      135          431     AdelaideBrousse@gustr.com     F
2      189          762        AdeleClavette@cuvox.de     F
3       15          150      AgateGrandbois@gustr.com     F
4      180          853          AgnesBriard@cuvox.de     F
..     ...          ...                           ...   ...
223     64          320          YvetteDAvis@cuvox.de     F
224    174          567   ZacharieDuplessis@rhyta.com     M
225    100          144   ZdenekVadnais@superrito.com     M
226    112          302          ZoeLeclair@gustr.com     F
227     53          615       ZurieTheberge@gustr.com     F

[228 rows x 4 columns]

identifiant                         email genre
0             39  AcelineHughes@jourrapide.com     F
1            431     AdelaideBrousse@gustr.com     F
2            762        AdeleClavette@cuvox.de     F
3            150      AgateGrandbois@gustr.com     F
4            853          AgnesBriard@cuvox.de     F
..           ...                           ...   ...
223          320          YvetteDAvis@cuvox.de     F
224          567   ZacharieDuplessis@rhyta.com     M
225          144   ZdenekVadnais@superrito.com     M
226          302          ZoeLeclair@gustr.com     F
227          615       ZurieTheberge@gustr.com     F

[228 rows x 3 columns]

L'exemple ci-dessous montre la différence entre indices et index :
- L' **indice** est la position dans le data frame.
- L' **index** est généré à l'init et identifie un élément.

Par conséquent, déplacer le 133 élément à la position 0 revient à modifier son indice de 132 à 0 alors que son index reste 132, à moins d'en forcer la modification comme indiqué au dessus.

La méthode **loc** permet de selectionner par **index** alors que **iloc** permet la selection par **indice**

## Agrégation de lignes

In [ ]:
# donnees de l'exercice, utile pour l'exemple
prets = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/prets.csv')
# prets['taux_endettement'] = round(prets['remboursement'] * 100 / prets['revenu'], 2)

# prets.rename(columns={'taux':'taux_interet'}, inplace=True)
# prets['cout_total'] = prets['remboursement'] * prets['duree']
# prets['benefices'] = round((prets['cout_total'] * prets['taux_interet']/100)/(24), 2)

# nombre_client_risque = prets.loc[(prets['taux_endettement'] > 35) & (prets['ville'] == 'PARIS'), :].shape[0]
# prets['risque'] = 'Non'
# prets.loc[prets['taux_endettement'] > 35, 'risque'] = 'Oui'

In [ ]:
prets.groupby('ville').sum()

identifiant       CP    revenu  remboursement  duree  \
ville                                                             
BORDEAUX          1718   531800   50816.0       15330.59   3660   
LYON              2833  1932134   95354.0       26064.67   6251   
MARSEILLE         7946   975732  145926.0       40895.72  16420   
NICE              2375   129100   85288.0       23544.24   4460   
PARIS             9849  5776019  335459.0       94052.61  16686   
TOULOUSE          3162   843300   75617.0       19286.18   5643   

                                                        type     taux  
ville                                                                  
BORDEAUX   immobilierimmobilierimmobilierimmobilierimmobi...   18.767  
LYON       immobilierimmobilierimmobilierimmobilierimmobi...   38.918  
MARSEILLE  immobilierimmobilierimmobilierimmobilierimmobi...   92.538  
NICE       immobilierimmobilierimmobilierimmobilierimmobi...   27.706  
PARIS      automobileimmobilierimmobilierimmobilierimmobi...  100.073  
TOULOUSE   immobilierimmobilierimmobilierimmobilierimmobi...   38.217

In [ ]:
prets.groupby(['ville', 'type']).sum()

identifiant       CP    revenu  remboursement  duree  \
ville     type                                                               
BORDEAUX  immobilier         1718   531800   50816.0       15330.59   3660   
LYON      automobile          360   207018   11531.0         788.80    131   
          immobilier         2473  1725116   83823.0       25275.87   6120   
MARSEILLE automobile          404    39031    5842.0         839.60    160   
          immobilier         7542   936701  140084.0       40056.12  16260   
NICE      automobile          187    12300    7607.0         612.80     80   
          immobilier         2188   116800   77681.0       22931.44   4380   
PARIS     automobile          612   375054   22834.0        1426.60    246   
          immobilier         9237  5400965  312625.0       92626.01  16440   
TOULOUSE  automobile          442    93400    7803.0         718.80    183   
          immobilier         2720   749900   67814.0       18567.38   5460   

                        taux  
ville     type                
BORDEAUX  immobilier  18.767  
LYON      automobile  10.083  
          immobilier  28.835  
MARSEILLE automobile   9.535  
          immobilier  83.003  
NICE      automobile   6.104  
          immobilier  21.602  
PARIS     automobile  17.271  
          immobilier  82.802  
TOULOUSE  automobile   9.868  
          immobilier  28.349

In [ ]:
prets.groupby(['ville', 'type'])['remboursement'].sum()

ville      type      
BORDEAUX   immobilier    15330.59
LYON       automobile      788.80
           immobilier    25275.87
MARSEILLE  automobile      839.60
           immobilier    40056.12
NICE       automobile      612.80
           immobilier    22931.44
PARIS      automobile     1426.60
           immobilier    92626.01
TOULOUSE   automobile      718.80
           immobilier    18567.38
Name: remboursement, dtype: float64

In [ ]:
agregat = prets.groupby('ville').agg({'remboursement': ['sum', 'mean'],
    'revenu': 'max'}) # utiliser plusieurs fonction d'agrégation

⚠ Avec groupby, les noms de villes deviennent ici les index

↪ Impossible d'utiliser 'ville' comme nom de colonne sans un reset_index

In [ ]:
print(agregat['remboursement'])
# print(aggregat['ville']) # non fonctionnel pour la raison citee au dessus

agregat_nouveaux_index = agregat.reset_index()
print(agregat_nouveaux_index)
print(agregat_nouveaux_index['ville'])

                sum         mean
ville                           
BORDEAUX   15330.59   958.161875
LYON       26064.67   930.881071
MARSEILLE  40895.72   545.276267
NICE       23544.24  1121.154286
PARIS      94052.61  1221.462468
TOULOUSE   19286.18   714.302963
       ville remboursement               revenu
                       sum         mean     max
0   BORDEAUX      15330.59   958.161875  3691.0
1       LYON      26064.67   930.881071  4771.0
2  MARSEILLE      40895.72   545.276267  2962.0
3       NICE      23544.24  1121.154286  5987.0
4      PARIS      94052.61  1221.462468  6807.0
5   TOULOUSE      19286.18   714.302963  3993.0
0     BORDEAUX
1         LYON
2    MARSEILLE
3         NICE
4        PARIS
5     TOULOUSE
Name: ville, dtype: object
